export const employees = [
  {
    id: "EMP001",
    name: "Alex Johnson",
    email: "alex.johnson@sumx.io",
    role: "Frontend Engineer",
    department: "Engineering",
    status: "Active",
    salary: 95000,
    joinDate: "2022-03-14",
    avatar: "AJ",
  },
  {
    id: "EMP002",
    name: "Maria Garcia",
    email: "maria.garcia@sumx.io",
    role: "Product Manager",
    department: "Product",
    status: "Active",
    salary: 110000,
    joinDate: "2021-07-01",
    avatar: "MG",
  },
  {
    id: "EMP003",
    name: "David Chen",
    email: "david.chen@sumx.io",
    role: "Backend Engineer",
    department: "Engineering",
    status: "On Leave",
    salary: 98000,
    joinDate: "2023-01-10",
    avatar: "DC",
  },
  {
    id: "EMP004",
    name: "Sarah Williams",
    email: "sarah.williams@sumx.io",
    role: "UX Designer",
    department: "Design",
    status: "Active",
    salary: 88000,
    joinDate: "2022-09-20",
    avatar: "SW",
  },
  {
    id: "EMP005",
    name: "James Miller",
    email: "james.miller@sumx.io",
    role: "Data Analyst",
    department: "Analytics",
    status: "Active",
    salary: 82000,
    joinDate: "2023-04-05",
    avatar: "JM",
  },
  {
    id: "EMP006",
    name: "Priya Patel",
    email: "priya.patel@sumx.io",
    role: "DevOps Engineer",
    department: "Engineering",
    status: "Inactive",
    salary: 105000,
    joinDate: "2020-11-18",
    avatar: "PP",
  },
  {
    id: "EMP007",
    name: "Carlos Torres",
    email: "carlos.torres@sumx.io",
    role: "Sales Executive",
    department: "Sales",
    status: "Active",
    salary: 75000,
    joinDate: "2024-01-02",
    avatar: "CT",
  },
  {
    id: "EMP008",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@sumx.io",
    role: "QA Engineer",
    department: "Engineering",
    status: "Active",
    salary: 79000,
    joinDate: "2023-08-15",
    avatar: "YT",
  },
  {
    id: "EMP009",
    name: "Nina Rossi",
    email: "nina.rossi@sumx.io",
    role: "Marketing Lead",
    department: "Marketing",
    status: "Active",
    salary: 91000,
    joinDate: "2021-05-22",
    avatar: "NR",
  },
  {
    id: "EMP010",
    name: "Omar Hassan",
    email: "omar.hassan@sumx.io",
    role: "Security Analyst",
    department: "Engineering",
    status: "On Leave",
    salary: 102000,
    joinDate: "2022-12-01",
    avatar: "OH",
  },
];

export const statCards = [
  { label: "Total Employees", value: "248", change: "+12%", trend: "up", icon: "Users" },
  { label: "Active Today", value: "194", change: "+3%", trend: "up", icon: "Activity" },
  { label: "On Leave", value: "18", change: "-5%", trend: "down", icon: "Calendar" },
  { label: "Avg. Salary", value: "$92,400", change: "+8%", trend: "up", icon: "DollarSign" },
];

export const DEPARTMENTS = ["Engineering", "Product", "Design", "Analytics", "Sales", "Marketing"];
export const STATUSES = ["Active", "Inactive", "On Leave"];
export const ROLES = [
  "Frontend Engineer",
  "Backend Engineer",
  "DevOps Engineer",
  "QA Engineer",
  "Product Manager",
  "UX Designer",
  "Data Analyst",
  "Sales Executive",
  "Marketing Lead",
  "Security Analyst",
];
